/iiwa2/controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    iiwa_arm_controller:
      type: position_controllers/JointGroupPositionController

/iiwa2/joint_state_broadcaster:
  ros__parameters:
    {}

/iiwa2/iiwa_arm_controller:
  ros__parameters:
    joints:
      - iiwa2_joint_a1
      - iiwa2_joint_a2
      - iiwa2_joint_a3
      - iiwa2_joint_a4
      - iiwa2_joint_a5
      - iiwa2_joint_a6
      - iiwa2_joint_a7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 30.0
    action_monitor_rate: 20.0